spring.application.name=AutomationEngine
server.servlet.context-path =/AutomationEngine
server.port =8080

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
# Set the root logging level to INFO
logging.level.root=INFO

# Set a specific package to DEBUG level
logging.level.com.example.app=DEBUG

# Enable a log file and specify the location
logging.file.name=myapp.log

# Customize the console log pattern
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

